#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: ax3600 (Xiaomi Devices) 23.5

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/AgustinLorenzo/openwrt.git
  REPO_BRANCH: main_nss
  REPO_TAG: ipq807x-nsswifi-2024-05-15-1806
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: configs/ax3600.config
  PATCH_FILES: configs/patches
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        git checkout tags/$REPO_TAG
        cd ..
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config

    - name: QoL fixes on default config
        run: |
          mkdir -p openwrt/files/etc/uci-defaults
          cat > files/etc/uci-defaults/99-qol_fixes << EOF
          uci set wireless.radio0.country='US'
          uci set wireless.radio1.country='US'
          uci set wireless.radio2.country='US'
          uci set wireless.radio1.disabled=0
          uci set wireless.radio2.disabled=0
          uci set pbuf.opt.memory_profile=auto
          uci set network.globals.packet_steering=0
          uci set firewall.@defaults[0].flow_offloading=0
          uci set ecm.@general[0].enable_bridge_filtering=0
          uci commit
          EOF

    - name: Download package sources
      run: |
        cd openwrt
        make download V=s

    - name: Build tools
      run: |
        cd openwrt
        make tools/install -j$(nproc) V=s || \
        make tools/install V=s

    - name: Build toolchain
      run: |
        cd openwrt
        make toolchain/install -j$(nproc) V=s || \
        make toolchain/install V=s

    - name: Build target images
      run: |
        cd openwrt
        make -j$(nproc) V=s || \
        make V=s

    - name: Get the current date
      run: echo "NOW=$(date +%F-%H%M)" >> $GITHUB_ENV

    - name: Create a release
      uses: "ncipollo/release-action@v1"
      with:
        name: "Updated prebuilt images (NSS-WiFi) ${{ env.NOW }}"
        commit: "main_nss"
        tag: "ipq807x-nsswifi-${{ env.NOW }}"
        generateReleaseNotes: true
        makeLatest: true
        artifacts: bin/targets/qualcommax/ipq807x/*
        token: "${{ secrets.GITHUB_TOKEN }}"