name: TEST GITHUB

on:
  workflow_dispatch:


jobs:

  GITHUB-Test:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: DevOpenWRT-Router/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'scripts'
          target-directory: 'output'
          destination-github-username: 'DevOpenWRT-Router'
          destination-repository-name: 'Linksys_OpenWRT_Releases'
          user-email: testbot@quasarfun.com
